services:
  - type: web
    name: beraka-ganaderia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    envVars:
      PYTHON_VERSION: 3.11